export interface MainCategoryItem {
  title: string
  slug: string
  url: string
}

export const CATEGORY_MAP: Record<'en' | 'ar' | 'ckb', MainCategoryItem[]> = {
  en: [
    { title: 'Case', slug: 'case', url: '/categories/case.png' },
    { title: 'Chair', slug: 'chair', url: '/categories/chair.png' },
    { title: 'CPU', slug: 'cpu', url: '/categories/cpu.png' },
    { title: 'Desktop', slug: 'desktop', url: '/categories/desktop.png' },
    { title: 'Fan', slug: 'fan', url: '/categories/fan.png' },
    { title: 'GPU', slug: 'gpu', url: '/categories/gpu.png' },
    { title: 'Keyboard', slug: 'keyboard', url: '/categories/keyboard.png' },
    { title: 'Laptop', slug: 'laptop', url: '/categories/laptop.png' },
    { title: 'Monitor', slug: 'monitor', url: '/categories/monitor.png' },
    { title: 'Motherboard', slug: 'motherboard', url: '/categories/motherboard.png' },
    { title: 'Mouse', slug: 'mouse', url: '/categories/mouse.png' },
    { title: 'PSU', slug: 'psu', url: '/categories/psu.png' },
    { title: 'RAM', slug: 'ram', url: '/categories/RAM.png' },
    { title: 'Speaker', slug: 'speaker', url: '/categories/speaker.png' },
    { title: 'Storage', slug: 'storage', url: '/categories/storage.png' },
    { title: 'Accessories', slug: 'accessories', url: '/categories/accessories.png' },
  ],
  ar: [
    { title: 'كيس حاسوب', slug: 'case', url: '/categories/case.png' },
    { title: 'كرسي', slug: 'chair', url: '/categories/chair.png' },
    { title: 'المعالج (CPU)', slug: 'cpu', url: '/categories/cpu.png' },
    { title: 'كمبيوتر مكتبي', slug: 'desktop', url: '/categories/desktop.png' },
    { title: 'مروحة', slug: 'fan', url: '/categories/fan.png' },
    { title: 'كرت الشاشة (GPU)', slug: 'gpu', url: '/categories/gpu.png' },
    { title: 'لوحة المفاتيح', slug: 'keyboard', url: '/categories/keyboard.png' },
    { title: 'لابتوب', slug: 'laptop', url: '/categories/laptop.png' },
    { title: 'شاشة', slug: 'monitor', url: '/categories/monitor.png' },
    { title: 'المذربورد', slug: 'motherboard', url: '/categories/motherboard.png' },
    { title: 'ماوس', slug: 'mouse', url: '/categories/mouse.png' },
    { title: 'مزود الطاقة (PSU)', slug: 'psu', url: '/categories/psu.png' },
    { title: 'الرام (RAM)', slug: 'ram', url: '/categories/RAM.png' },
    { title: 'سماعة', slug: 'speaker', url: '/categories/speaker.png' },
    { title: 'وحدات التخزين', slug: 'storage', url: '/categories/storage.png' },
    { title: 'إكسسوارات', slug: 'accessories', url: '/categories/accessories.png' },
  ],
  ckb: [
    { title: 'کەیس', slug: 'case', url: '/categories/case.png' },
    { title: 'کورسی', slug: 'chair', url: '/categories/chair.png' },
    { title: 'پڕۆسێسەر (CPU)', slug: 'cpu', url: '/categories/cpu.png' },
    { title: 'کۆمپیوتەری دێسکتۆپ', slug: 'desktop', url: '/categories/desktop.png' },
    { title: 'پانکه / سپینەر', slug: 'fan', url: '/categories/fan.png' },
    { title: 'کارتی شاشە (GPU)', slug: 'gpu', url: '/categories/gpu.png' },
    { title: 'کیبۆرد', slug: 'keyboard', url: '/categories/keyboard.png' },
    { title: 'لابتۆپ', slug: 'laptop', url: '/categories/laptop.png' },
    { title: 'شاشە / مۆنیتەر', slug: 'monitor', url: '/categories/monitor.png' },
    { title: 'مەزەربۆرد', slug: 'motherboard', url: '/categories/motherboard.png' },
    { title: 'ماوس', slug: 'mouse', url: '/categories/mouse.png' },
    { title: 'پاوەر سەپلای (PSU)', slug: 'psu', url: '/categories/psu.png' },
    { title: 'مێمۆری (RAM)', slug: 'ram', url: '/categories/RAM.png' },
    { title: 'سپیكەر / دەنگنەر', slug: 'speaker', url: '/categories/speaker.png' },
    { title: 'بیرگە / خەزن', slug: 'storage', url: '/categories/storage.png' },
    { title: 'ئێکسسوارات', slug: 'accessories', url: '/categories/accessories.png' },
  ],
}
