export interface SubCategoryItem {
  title: string
  slug: string
}

export interface CategoryGroup {
  title: string
  // If slug is provided, it behaves as an independent direct link (like Laptop or Monitor).
  // If null, it is a main container and clicking it toggles a dropdown instead.
  slug?: string | null
  subCategories?: SubCategoryItem[]
}

export const MAIN_CATEGORY_GROUPS: Record<'en' | 'ar' | 'ckb', CategoryGroup[]> = {
  en: [
    {
      title: 'Computer Parts',
      slug: null,
      subCategories: [
        { title: 'CPU', slug: 'cpu' },
        { title: 'GPU', slug: 'gpu' },
        { title: 'Motherboard', slug: 'motherboard' },
        { title: 'RAM', slug: 'ram' },
        { title: 'Power Supply (PSU)', slug: 'psu' },
        { title: 'Case', slug: 'case' },
        { title: 'CPU Cooler', slug: 'cooler' },
        { title: 'Case Fan', slug: 'fan' },
        { title: 'Thermal Paste', slug: 'thermal-paste' },
      ],
    },
    {
      title: 'Storage',
      slug: null,
      subCategories: [
        { title: 'M.2 SSD', slug: 'm2' },
        { title: 'SATA SSD', slug: 'ssd' },
        { title: 'HDD', slug: 'hdd' },
        { title: 'External SSD', slug: 'external-ssd' },
        { title: 'External HDD', slug: 'external-hdd' },
        { title: 'Flash USB', slug: 'flash-usb' },
        { title: 'SD Card', slug: 'sd-card' },
      ],
    },
    {
      title: 'Laptop',
      slug: 'laptop',
    },
    {
      title: 'Monitor',
      slug: 'monitor',
    },
    {
      title: 'Accessories',
      slug: null,
      subCategories: [
        { title: 'Headset', slug: 'headset' },
        { title: 'Speaker', slug: 'speaker' },
        { title: 'Keyboard', slug: 'keyboard' },
        { title: 'Mouse', slug: 'mouse' },
        { title: 'Microphone', slug: 'mic' },
        { title: 'Earphone', slug: 'earphone' },
        { title: 'Webcam', slug: 'webcam' },
        { title: 'Mouse Pad', slug: 'pad' },
        { title: 'Monitor Stand', slug: 'monitor-stand' },
        { title: 'Headset Stand', slug: 'headset-stand' },
        { title: 'Stand Mic', slug: 'stand-mic' },
      ],
    },
    {
      title: 'Other',
      slug: null,
      subCategories: [
        { title: 'Chair', slug: 'chair' },
        { title: 'Desk', slug: 'desk' },
        { title: 'UPS', slug: 'ups' },
        { title: 'UPS Battery', slug: 'ups-battery' },
        { title: 'Controller', slug: 'controller' },
        { title: 'Steering Wheel', slug: 'steering-wheel' },
        { title: 'VR', slug: 'vr' },
        { title: 'Router', slug: 'router' },
        { title: 'Network', slug: 'network' },
        { title: 'Cable', slug: 'cable' },
        { title: 'Adapter', slug: 'adapter' },
        { title: 'Hard Cover', slug: 'hard-cover' },
        { title: 'Laptop Ram', slug: 'laptop-ram' },
        { title: 'Laptop Cooling Pad', slug: 'laptop-cooling-pad' },
        { title: 'TV Box', slug: 'tv-box' },
        { title: 'Printer', slug: 'printer' },
        { title: 'Bag', slug: 'bag' },
        { title: 'Gift Card', slug: 'gift-card' },
      ],
    },
  ],
  ar: [
    {
      title: 'قطع الكمبيوتر',
      slug: null,
      subCategories: [
        { title: 'المعالج (CPU)', slug: 'cpu' },
        { title: 'كرت الشاشة (GPU)', slug: 'gpu' },
        { title: 'المذربورد', slug: 'motherboard' },
        { title: 'الرام (RAM)', slug: 'ram' },
        { title: 'مزود الطاقة (PSU)', slug: 'psu' },
        { title: 'كيس حاسوب', slug: 'case' },
        { title: 'مبرد المعالج', slug: 'cooler' },
        { title: 'مروحة كيس', slug: 'fan' },
        { title: 'معجون حراري', slug: 'thermal-paste' },
      ],
    },
    {
      title: 'التخزين',
      slug: null,
      subCategories: [
        { title: 'M.2 SSD', slug: 'm2' },
        { title: 'SATA SSD', slug: 'ssd' },
        { title: 'HDD', slug: 'hdd' },
        { title: 'SSD خارجي', slug: 'external-ssd' },
        { title: 'HDD خارجي', slug: 'external-hdd' },
        { title: 'فلاش ميموري', slug: 'flash-usb' },
        { title: 'بطاقة ذاكرة SD', slug: 'sd-card' },
      ],
    },
    {
      title: 'لابتوب',
      slug: 'laptop',
    },
    {
      title: 'شاشة',
      slug: 'monitor',
    },
    {
      title: 'إكسسوارات',
      slug: null,
      subCategories: [
        { title: 'سماعة رأس', slug: 'headset' },
        { title: 'مكبر صوت', slug: 'speaker' },
        { title: 'لوحة المفاتيح', slug: 'keyboard' },
        { title: 'ماوس', slug: 'mouse' },
        { title: 'ميكروفون', slug: 'mic' },
        { title: 'سماعة أذن', slug: 'earphone' },
        { title: 'كاميرا ويب', slug: 'webcam' },
        { title: 'ماوس باد', slug: 'pad' },
        { title: 'حامل شاشة', slug: 'monitor-stand' },
        { title: 'حامل سماعة', slug: 'headset-stand' },
        { title: 'حامل ميكروفون', slug: 'stand-mic' },
      ],
    },
    {
      title: 'أخرى',
      slug: null,
      subCategories: [
        { title: 'كرسي', slug: 'chair' },
        { title: 'طاولة مكتب', slug: 'desk' },
        { title: 'UPS', slug: 'ups' },
        { title: 'بطارية UPS', slug: 'ups-battery' },
        { title: 'قبضة تحكم', slug: 'controller' },
        { title: 'مقود ألعاب', slug: 'steering-wheel' },
        { title: 'نظارة واقع افتراضي VR', slug: 'vr' },
        { title: 'راوتر', slug: 'router' },
        { title: 'شبكات', slug: 'network' },
        { title: 'كابلات', slug: 'cable' },
        { title: 'محول', slug: 'adapter' },
        { title: 'غطاء حماية', slug: 'hard-cover' },
        { title: 'رام لابتوب', slug: 'laptop-ram' },
        { title: 'قاعدة تبريد لابتوب', slug: 'laptop-cooling-pad' },
        { title: 'تي في بوكس', slug: 'tv-box' },
        { title: 'طابعة', slug: 'printer' },
        { title: 'حقيبة', slug: 'bag' },
        { title: 'بطاقة هدايا', slug: 'gift-card' },
      ],
    },
  ],
  ckb: [
    {
      title: 'بەشەکانی کۆمپیوتەر',
      slug: null,
      subCategories: [
        { title: 'پڕۆسێسەر (CPU)', slug: 'cpu' },
        { title: 'کارتی شاشە (GPU)', slug: 'gpu' },
        { title: 'مەزەربۆرد', slug: 'motherboard' },
        { title: 'مێمۆری (RAM)', slug: 'ram' },
        { title: 'پاوەر سەپلای (PSU)', slug: 'psu' },
        { title: 'کەیس', slug: 'case' },
        { title: 'ساردکەرەوەی CPU', slug: 'cooler' },
        { title: 'پانکەی کەیس', slug: 'fan' },
        { title: 'مەعجونی گەرمی', slug: 'thermal-paste' },
      ],
    },
    {
      title: 'بیرگە و خەزن',
      slug: null,
      subCategories: [
        { title: 'M.2 SSD', slug: 'm2' },
        { title: 'SATA SSD', slug: 'ssd' },
        { title: 'HDD', slug: 'hdd' },
        { title: 'SSD دەرەکی', slug: 'external-ssd' },
        { title: 'HDD دەرەکی', slug: 'external-hdd' },
        { title: 'فلاش میمۆری', slug: 'flash-usb' },
        { title: 'SD کارت', slug: 'sd-card' },
      ],
    },
    {
      title: 'لابتۆپ',
      slug: 'laptop',
    },
    {
      title: 'شاشە / مۆنیتەر',
      slug: 'monitor',
    },
    {
      title: 'ئێکسسوارات',
      slug: null,
      subCategories: [
        { title: 'هێدسێت', slug: 'headset' },
        { title: 'سپیکەر', slug: 'speaker' },
        { title: 'کیبۆرد', slug: 'keyboard' },
        { title: 'ماوس', slug: 'mouse' },
        { title: 'مایکرۆفۆن', slug: 'mic' },
        { title: 'ئەیرفۆن', slug: 'earphone' },
        { title: 'وێبکام', slug: 'webcam' },
        { title: 'ماوس پاد', slug: 'pad' },
        { title: 'ستاندی مۆنیتەر', slug: 'monitor-stand' },
        { title: 'ستاندی هێدسێت', slug: 'headset-stand' },
        { title: 'ستاندی مایکرۆفۆن', slug: 'stand-mic' },
      ],
    },
    {
      title: 'ئەوانی تر',
      slug: null,
      subCategories: [
        { title: 'کورسی', slug: 'chair' },
        { title: 'مێزی کار', slug: 'desk' },
        { title: 'یو پی ئێس (UPS)', slug: 'ups' },
        { title: 'باتری UPS', slug: 'ups-battery' },
        { title: 'کۆنترۆڵەر', slug: 'controller' },
        { title: 'سوکان', slug: 'steering-wheel' },
        { title: 'جاوی VR', slug: 'vr' },
        { title: 'ڕاوتەر', slug: 'router' },
        { title: 'ئامێری نێتۆرک', slug: 'network' },
        { title: 'کێبڵ', slug: 'cable' },
        { title: 'ئەداپتەر', slug: 'adapter' },
        { title: 'بەرگی پارێزەر', slug: 'hard-cover' },
        { title: 'ڕامی لابتۆپ', slug: 'laptop-ram' },
        { title: 'پادی فێنککەرەوەی لابتۆپ', slug: 'laptop-cooling-pad' },
        { title: 'تی ڤی بۆکس', slug: 'tv-box' },
        { title: 'پرینتەر', slug: 'printer' },
        { title: 'جانتا', slug: 'bag' },
        { title: 'گیفت کارت', slug: 'gift-card' },
      ],
    },
  ],
}
