/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    media: Media;
    categories: Category;
    'ui-categories': UiCategory;
    'ui-products': UiProduct;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'ui-categories': UiCategoriesSelect<false> | UiCategoriesSelect<true>;
    'ui-products': UiProductsSelect<false> | UiProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ckb' | 'en' | 'ar') | ('ckb' | 'en' | 'ar')[];
  globals: {
    'general-settings': GeneralSetting;
  };
  globalsSelect: {
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
  };
  locale: 'ckb' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: string | null;
  barcode?: string | null;
  code?: string | null;
  brand?: string | null;
  price: number;
  priceIQD?: number | null;
  stock: number;
  condition: 'new' | 'used' | 'refurbished' | 'open_box' | 'used_like_new' | 'used_no_box';
  category: number | Category;
  hasDiscount?: boolean | null;
  discountType?: ('fixed' | 'percentage') | null;
  discountValue?: number | null;
  technicalSpecs?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  imagesGallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Used in the URL (e.g., cpu, computer-parts)
   */
  slug: string;
  /**
   * Leave empty if this is a top-level Main Category.
   */
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-categories".
 */
export interface UiCategory {
  id: number;
  title: string;
  /**
   * Used for direct links (e.g., laptop, monitor). Leave empty if this is a main container.
   */
  slug?: string | null;
  isContainer?: boolean | null;
  /**
   * If checked, this category will be ignored when fetching categories for UI carousels.
   */
  hideInCarousel?: boolean | null;
  subCategories?:
    | {
        title: string;
        /**
         * Slug matching the external ERP/db category slug (e.g., cpu, gpu).
         */
        slug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used to control horizontal sorting in the UI.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-products".
 */
export interface UiProduct {
  id: number;
  title: string;
  /**
   * Used for direct URLs (e.g., /laptops/custom-bundle). Checked against Products so it remains unique.
   */
  slug?: string | null;
  /**
   * Optional direct price for this UI banner/offer card.
   */
  price?: number | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Determines where or how this item is displayed (e.g., Offers, Promotions, Banners).
   */
  uiCategory: number | UiCategory;
  /**
   * Optional CRM/DB Category mapping if this UI item targets a specific catalog category.
   */
  category?: (number | null) | Category;
  /**
   * Choose what happens when the user clicks this item.
   */
  linkType?: ('none' | 'product' | 'static') | null;
  /**
   * Select the CRM product this item points to.
   */
  linkedProduct?: (number | null) | Product;
  /**
   * Enter a custom route (e.g. /custom-landing) or external URL (https://...).
   */
  staticUrl?: string | null;
  /**
   * Sorting priority within its UI Category.
   */
  order?: number | null;
  /**
   * Optional arbitrary key-value payload for custom UI attributes (badge labels, custom colors, specs).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  isActive?: boolean | null;
  textColor?: ('light' | 'dark') | null;
  bannerHeight: 'small' | 'medium' | 'large';
  mediaType: 'image' | 'svg' | 'video';
  title: string;
  description?: string | null;
  backgroundImage?: (number | null) | Media;
  /**
   * Paste inline <svg> markup or external SVG URL here
   */
  backgroundSvg?: string | null;
  /**
   * Upload MP4 / WebM file from media gallery
   */
  backgroundVideo?: (number | null) | Media;
  enableLink?: boolean | null;
  linkUrl?: string | null;
  linkLabel?: string | null;
  openInNewTab?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'ui-categories';
        value: number | UiCategory;
      } | null)
    | ({
        relationTo: 'ui-products';
        value: number | UiProduct;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  barcode?: T;
  code?: T;
  brand?: T;
  price?: T;
  priceIQD?: T;
  stock?: T;
  condition?: T;
  category?: T;
  hasDiscount?: T;
  discountType?: T;
  discountValue?: T;
  technicalSpecs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  featuredImage?: T;
  imagesGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-categories_select".
 */
export interface UiCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isContainer?: T;
  hideInCarousel?: T;
  subCategories?:
    | T
    | {
        title?: T;
        slug?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-products_select".
 */
export interface UiProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  price?: T;
  description?: T;
  image?: T;
  uiCategory?: T;
  category?: T;
  linkType?: T;
  linkedProduct?: T;
  staticUrl?: T;
  order?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  isActive?: T;
  textColor?: T;
  bannerHeight?: T;
  mediaType?: T;
  title?: T;
  description?: T;
  backgroundImage?: T;
  backgroundSvg?: T;
  backgroundVideo?: T;
  enableLink?: T;
  linkUrl?: T;
  linkLabel?: T;
  openInNewTab?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: number;
  slogan?: string | null;
  logo?: (number | null) | Media;
  /**
   * Used across the system to calculate IQD pricing dynamically.
   */
  exchangeRate: number;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'tiktok' | 'whatsapp' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  slogan?: T;
  logo?: T;
  exchangeRate?: T;
  email?: T;
  phone?: T;
  address?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}